name: Deploy to Netlify

on:
  push:
    branches:
      - dev  # Change this to your default branch name if it's different

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Clean npm cache
        run: npm cache clean --force

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npm run lint
        continue-on-error: ${{ github.ref == 'refs/heads/dev' }}

      - name: Build the project
        run: |
          CI=false npm run build

      - name: Install Netlify CLI
        run: npm install -g netlify-cli

      - name: Deploy to Netlify
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }} # Ensure this is added to your GitHub secrets
        run: netlify deploy --prod --dir=build